### PR TITLE
Deprecate Analyse_SAR.OSLdata() in favour of analyse_SAR.CWOSL()

### LINKED ISSUE #216: Analyse_SAR.OSLdata() should point to analyse_SAR.CWOSL()
Starting with a capital letter, `Analyse_SAR.OSLdata()` is named inconsistently. I suggest renaming it to `analyse_SAR.OSLdata()`, leaving a stub with the old name that calls the newly-named function and throws a warning.

### PR DESCRIPTION
**Pull request by mcol**
Fixes #216.

### CODE REVIEW

**Comment by RLumSK** [comment]
@mcol Sorry, please do not rename it as the function names are case sensitive. Just deprecated is fine.

**Comment by mcol** [comment]
I don't understand: if we deprecate the `Analyse` version without an `analyse` version, users won't have a way to avoid the warning. With my changes, both versions will work.

Or do you mean that the filename should not be renamed? But that's just an internal thing, it shouldn't have any impact when the package is built.

**Comment by mcol** [comment]
I see, it should point to `analyse_SAR.CWOSL()`, sorry I've overlooked it from the discussion in #216.

**Comment by RLumSK** [comment]
No, I mean that the function name must not change. It should stay `Analyse_SAR.OSLdata()` and the entire function gets deprecated and the user should use `analyse_SAR.CWOSL()` instead. This anyway was the idea of `analyse_SAR.CWOSL()` because a couple of things were not done well in `Analyse_SAR.OSLdata()`.

**Pull request merged**
